- name: inventory variables
  hosts: local
  connection: local
  tasks:
  - name: print the course info
    ansible.builtin.debug:
      msg: "Hello, course is: {{ COURSE }}, Duration is: {{ DURATION }}, Name is: {{ NAME }}, Tools is: {{ TOOL }}"